### ISSUE TITLE
Empty string breaks expected child object mapping

### ISSUE THREAD

**Issue by lancefrench** [digitalocean/kartograph#13]
Before I begin, I understand that JSON has a null value representation and the API I am working with is doing things "wrong," but I am stuck with them.  Here's what I'm dealing with in a typical API response:

``` json
json = '{
  "Emails": {
    "ContactEmail": {
      "address": "user@address.com",
      "useType": "Primary"
    }
  }
}'

json_empty = '{
  "Emails": ""
}'
```

Depending on whether or not the child attribute of `ContactEmail` is populated or not (if a customer has an email address in the system), I either get an array or an empty string.  Kartograph currently expects something it can understand and map, or a `nil` value.

My workaround for this was to add an `return if object.empty?` check to the existing `object.nil?` check in `/lib/kartograph/property.rb:34` to avoid seeing a `has_key?' for "":String (NoMethodError)` during mapping the `ContactEmail` (child).

This seems like the exact sort of hack that will have unintended consequences, so before I submit a pull request I wanted to put this use case out there and see if you all had any thoughts.  Is this sort "bad" JSON something you want to be flexible enough to support?

Note: I have no intention of trying to support this JSON syntax for create operations.  I'm just trying to read in data.

**Comment by lancefrench** [comment]
Closing this out.  It turns out that the API I am using offers XML output.  If I really wanted to clean up JSON rendering of `nil` I could process an XML `response.body` into proper JSON before passing it in to the handler.  This, while nuts, seems preferable to adding a hack in `property.rb`.

Sadly, Kartograph has become unusable because my API sends `singular` and `plural` responses under the same `root_key` text.

**Comment by lancefrench** [comment]
Actually, I am going to reopen this issue.  Would you accept a small pull request for returning if `property.rb` runs into an empty string?

**Comment by phillbaker** [comment]
@lancefrench seems like the inverse of https://github.com/digitalocean/kartograph/pull/5 actually - might be a good conceptual starting point. It looks like we went with specifying an explicit option, if you wanted to submit a PR along those lines I think that'd work.

**Comment by lancefrench** [comment]
Closing out issues that I won't be revisiting.  Your idea of an explicit option was great, I just ran out of time on the project I was working on to come back and implement.
