### ISSUE TITLE
Support apis that use idential root_key for plural and singular attributes

### ISSUE THREAD

**Issue by lancefrench** [digitalocean/kartograph#20]
This is an example from a retail point of sale API I was using Kartograph to wrap last year:

User with one email address:

```
{
    "Emails": {
        "ContactEmail": {
            "address": "user1@gmail.com",
            "useType": "Primary"
        }
    }
}
```

User with two, or more, addresses:

```
{
    "Emails": {
        "ContactEmail": [{
            "address": "user2@icloud.com",
            "useType": "Primary"
        }, {
            "address": "user2@gmail.com",
            "useType": "Secondary"
        }]
    }
}
```

Here `ContactEmail` is used as the root key in both the plural and singular use cases.  If processed, you will run into a `has_key?` for Array exception generate in the property.rb [value_from](https://github.com/lancefrench/kartograph/blob/master/lib/kartograph/property.rb#L34) method.

I used a hack to get around the exceptions that threw away additional array members effectively forcing my ContactEmail property to be singular, but I think a better approach is to allow Kartograph to force `plural` where specified.  That is, if I specify `plural` in a model that Kartograph should make a best attempt to cast the read property value as an array.

It's possible that Kartograph is not the place to make this effort and that `plural` could be removed in favor of letting Virtus mappings handle special coercion use cases, but I thought I would post this here in case any one had better ideas.

**Comment by driv3r** [comment]
as far as I understand the inner workings, it should be enough for you to pass in `plural: true` option, i.e.

```ruby
class EmailsMapping
  include Kartograph::DSL

  kartograph do
    root_key singular: "Emails"
    
    # NOTE Here you need to specify plural: true
    propert "ContactEmail", plural: true, scopes: [:your_scopes] do
      mapping ContactEmail
      property "adress", scopes: [:your_scopes]
      property "useType", scopes: [:your_scopes]
    end
  end
end
```

Thanks to this option, kartograph [will always try to make an array from value](https://github.com/digitalocean/kartograph/blob/master/lib/kartograph/property.rb#L62)

```ruby
def sculpt_value(value, scope)
  plural? ? Array(value).map {|v| Sculptor.new(v, map).sculpt(scope) } : Sculptor.new(value, map).sculpt(scope)
end
```

**Comment by lancefrench** [comment]
You can't specify a default of plural because it blows up where your response is not an Array during mapping.  The code has to be smart enough to look at the response and set up the appropriate data structure.

I'm going to close this out because it's unlikely that I will come back to it.  This problem existed in trying to service the Lightspeed POS API responses in case any one else comes looking.
